# TCL File Generated by Component Editor 12.1sp1
# Wed Nov 20 19:39:53 CET 2013
# DO NOT MODIFY


# 
# Ultrasound_interface "Ultrasound_interface" v1.0
# null 2013.11.20.19:39:53
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module Ultrasound_interface
# 
set_module_property NAME Ultrasound_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME Ultrasound_interface
set_module_property TOP_LEVEL_HDL_FILE Ultrasound_interface.v
set_module_property TOP_LEVEL_HDL_MODULE Ultrasound_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME Ultrasound_interface
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file Ultrasound_interface.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 
add_parameter idle STD_LOGIC_VECTOR 1
set_parameter_property idle DEFAULT_VALUE 1
set_parameter_property idle DISPLAY_NAME idle
set_parameter_property idle TYPE STD_LOGIC_VECTOR
set_parameter_property idle UNITS None
set_parameter_property idle ALLOWED_RANGES 0:31
set_parameter_property idle HDL_PARAMETER true
add_parameter trigger STD_LOGIC_VECTOR 2
set_parameter_property trigger DEFAULT_VALUE 2
set_parameter_property trigger DISPLAY_NAME trigger
set_parameter_property trigger TYPE STD_LOGIC_VECTOR
set_parameter_property trigger UNITS None
set_parameter_property trigger ALLOWED_RANGES 0:31
set_parameter_property trigger HDL_PARAMETER true
add_parameter wait_feedback STD_LOGIC_VECTOR 4
set_parameter_property wait_feedback DEFAULT_VALUE 4
set_parameter_property wait_feedback DISPLAY_NAME wait_feedback
set_parameter_property wait_feedback TYPE STD_LOGIC_VECTOR
set_parameter_property wait_feedback UNITS None
set_parameter_property wait_feedback ALLOWED_RANGES 0:31
set_parameter_property wait_feedback HDL_PARAMETER true
add_parameter measure_feedback STD_LOGIC_VECTOR 8
set_parameter_property measure_feedback DEFAULT_VALUE 8
set_parameter_property measure_feedback DISPLAY_NAME measure_feedback
set_parameter_property measure_feedback TYPE STD_LOGIC_VECTOR
set_parameter_property measure_feedback UNITS None
set_parameter_property measure_feedback ALLOWED_RANGES 0:31
set_parameter_property measure_feedback HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end feedback_in export Input 1
add_interface_port conduit_end trigger_out export Output 1


